### PR TITLE
Changes on README regarding hawkinit

### PR DESCRIPTION
**Pull request by josejulio**
- Hawkinit is now under Hawkular umbrella.
- Added basic scenarios for hawkinit

### CODE REVIEW

**Comment by abonas** [comment]
@josejulio why is this on @cfcosta fork? you can send a PR to the repo on manageiq basing it on the PR there (on top of it)

**Comment by josejulio** [comment]
Mainly to include it on his PR as soon as possible, to avoid having two separate discussions for longer than needed.

**Comment by josejulio** [comment]
@cfcosta are ok on merging this? We can further discuss it on the main PR.

**Comment by josejulio** [comment]
Thanks!

**Pull request merged**
